import type { Metadata } from "next";
import { Alegreya, Alegreya_Sans, Alfa_Slab_One, Inter, Rubik_Glitch, Sofia_Sans_Semi_Condensed } from "next/font/google";
import "./globals.css";

const fonts = Alegreya({ 
  subsets: ["latin"], 
  weight:'600'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.className}>{children}</body>
    </html>
  );
}
